server:
  port: ${USER_SERVER_PORT:9696}

spring:
  config:
    import: "optional:classpath:.env"

  datasource:
    url: ${USER_DB_URL:jdbc:postgresql://localhost:5432/user-service}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topics:
      user-created: ${KAFKA_TOPIC_USER_CREATED:user-created}

  jpa:
    hibernate:
      default_schema: public
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8085/realms/booking-app}

  liquibase:
    default_schema: public
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

springdoc:
  api-docs:
    path: /api-docs/user
  swagger-ui:
    path: /swagger/user
    oauth:
      client-id: ${SWAGGER_CLIENT_ID:frontend}
      client-secret: ${SWAGGER_CLIENT_SECRET:hHkmOltodovvM0UJvccbcyk57TxVpHrr}

keycloak:
  realm: ${KEYCLOAK_REALM:booking-app}
  serverUrl: ${KEYCLOAK_SERVER_URL:http://localhost:8085}
  client:
    service-client:
      client-id: ${KEYCLOAK_SERVICE_CLIENT_ID:user-service-admin}
      client-secret: ${KEYCLOAK_SERVICE_CLIENT_SECRET:hFgYVWhC7TZZiSILOj289Zr8IAYHl3Qo}