events {}

http {

    proxy_connect_timeout 10s;
    proxy_read_timeout 10s;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Authorization $http_authorization;

    upstream user_service {server user-service:9696;}
    upstream restaurant_service {server restaurant-service:9797;}
    upstream review_service {server review-service:9898;}
    upstream booking_service {server booking-service:9999;}

    upstream keycloak {
        server keycloak:8080;
    }

    server {
        listen 80;
        root /usr/share/nginx/html;

        location /api/v2/users/ {proxy_pass http://user_service/api/v2/users/;}
        location /api/v2/users {proxy_pass http://user_service/api/v2/users;}
        location /swagger/user/ {proxy_pass http://user_service/swagger/user/;}
        location /api-docs/user/ {proxy_pass http://user_service/api-docs/user/;}

        location /api/v2/restaurant {proxy_pass http://restaurant_service/api/v2/restaurant;}
        location /api/v2/restaurant/ {proxy_pass http://restaurant_service/api/v2/restaurant/;}
        location /swagger/restaurant/ {proxy_pass http://restaurant_service/swagger/restaurant/;}
        location /api-docs/restaurant/ {proxy_pass http://restaurant_service/api-docs/restaurant/;}

        location /api/v2/review {proxy_pass http://review_service/api/v2/review;}
        location /api/v2/review/ {proxy_pass http://review_service/api/v2/review/;}
        location /swagger/review/ {proxy_pass http://review_service/swagger/review/;}
        location /api-docs/review/ {proxy_pass http://review_service/api-docs/review/;}

        location /api/v2/booking {proxy_pass http://booking_service/api/v2/booking;}
        location /api/v2/booking/ {proxy_pass http://booking_service/api/v2/booking/;}
        location /swagger/booking/ {proxy_pass http://booking_service/swagger/booking/;}
        location /api-docs/booking/ {proxy_pass http://booking_service/api-docs/booking/;}

        location /realms/ {
            proxy_pass http://keycloak/realms/;
            proxy_set_header Host nginx;
        }

        location / {
            try_files /hello.html =404;
        }

    }
}